'use strict';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const CREATE_ACCOUNT = 'CREAT_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREAT_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAIL = 'CREAT_ACCOUNT_FAIL';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL';

export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_SUCCESS= 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAIL = 'EDIT_CATEGORY_FAIL';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const GET_DECKS = 'GET_DECKS';
export const GET_DECKS_SUCCESS = 'GET_DECK_SUCCESS';
export const GET_DECKS_FAIL = 'GET_DECK_FAIL';

export const GET_FLASHCARDS = 'GET_FLASHCARDS';
export const GET_FLASHCARDS_SUCCESS = 'GET_FLASHCARDS_SUCCESS';
export const GET_FLASHCARDS_FAIL = 'GET_FLASHCARDS_FAIL';

export const LOG_OUT = 'LOG_OUT';
export const REQUEST = 'REQUEST';
